import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { api } from "~/utils/api";

const intrestYear = []



export default function Home() {

  const [year,setYear] = useState("0");
  const [intrest,setIntrest] = useState("0");
  const [kapital, setKapital] = useState("0")
  const [result, setResult] = useState("0")

function showYears(){
  setYear(year)
  setIntrest(intrest)
  setKapital(kapital)
  const res = String(Number(kapital) * (1 + Number(intrest)/100)**Number(year))

  setResult(res)
  console.log(year)
  console.log(intrest)
  console.log(String(res))
}


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
       <div>
        <h1>Intrest Calculator</h1>
        <div className="">
          <div>
          <label htmlFor="Kapital">Kapital</label>
          <input type="number" placeholder="Kapital" className="bg-slate-100 m-8" value={kapital}
                onChange={e => setKapital(e.target.value)} />
          </div>
          <div>
          <label htmlFor="">Years</label>
          <input type="number" placeholder="Years" className="bg-slate-100 m-8" value={year}
                onChange={e => setYear(e.target.value)} />
          </div>
          <div>
          <label htmlFor="">Intrest in Percent</label>
          <input type="number" placeholder="Intrest" className="bg-slate-100 m-8" value={intrest}
                onChange={e => setIntrest(e.target.value)} />
          </div>
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" onClick={showYears}>Calculate</button>
          
          <h1>{result}</h1>
        </div>
        

       </div>
      </main>
    </>
  );
}
